### PR TITLE
Splited erlang code from c code to simplify adding erlang app to project.

### PR DESCRIPTION
**Pull request by vesperusiak**
I had to change the name of application because of conflict with rebar conventions (couldn't name repo same as root project).
If you want me to transfer ownership of erld_erlang_app repo to you, I can do this, just ask.

### CODE REVIEW

**Comment by bernardd** [comment]
Hi vesperusiak,
Apologies for taking so long to get back to you - I've been travelling and working and all the other standard excuses. Plus I had to go and learn what git submodules were :)
In the end, though, I think this is probably a worthwhile change. If you're still happy to transfer ownership of erld_erlang_app to me, that would be great (just so that the two parts are kept in the one place). Once that's done, I'll merge in the pull request (I just don't want to do it before because I'd rather people didn't have to look in two separate places to get the bits they need to get it going).

Cheers.

**Comment by ibnfirnas** [comment]
What are the advantages of this change?

**Comment by bernardd** [comment]
It means that the section of code that needs to be included in your Erlang app can be pulled in in isolation, while erld itself can be built separately.

**Comment by ibnfirnas** [comment]
@bernardd Right, this is how it works. What I couldn't readily think of, is when would someone want to do this with `erld`? Is there an example use-case?

**Comment by bernardd** [comment]
@ibnfirnas vesperusiak says it can cause problems when using erlang.mk to have C code in the tree, which sounds reasonable enough. If you're able to just pull in the Erlang part to your erlang code and the C part to somewhere (or nowhere) else that seems like a neat way to solve it.

**Pull request merged**
